- hosts: victor
  vars:
    USER: "{{ user_perm }}"
    HTTP_PORT: "10080"
    SSH_PORT: "10022"
    DB_USER: "root"
    DB_PASS: "Cdt@12345678"
    DB_NAME: "gitlabhq_production"
    GITLAB_HOST: "{{ gitlab_host }}"
    GITLAB_ROOT_PASS: "{{ gitlab_root_pass }}"
    SECRETS_DB_KEY_BASE: "secret-db-key-base"
    SECRETS_SECRET_KEY_BASE: "secret-key-base"
    SECRETS_OTP_KEY_BASE: "secret-otp-key-base"
    OPENSHIFT_PUBLIC_HOSTNAME: "tt1.eastus.cloudapp.azure.com"
    OPENSHIFT_ROUTING_SUFFIX: "40.117.95.16"
  become: yes
  tasks:
    - name: "Instalando yum utils"
      yum:
        name: yum-utils
        state: latest

    - name: "Instalando device-mapper-persistent-data"
      yum:
        name: device-mapper-persistent-data
        state: latest

    - name: "Instalando lvm2"
      yum:
        name: lvm2
        state: latest

    - name: "Adicionando repositório do Docker"
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      become: yes

    - name: "Habilitando repositório Docker Edge"
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-edge'
        option: enabled
        value: 0
      become: yes

    - name: "Habilitando repositório Docker Test"
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-test'
        option: enabled
        value: 0
      become: yes

    - name: "Instalando o docker"
      package:
        name: docker-ce
        state: latest
      become: yes

    - name: "Iniciando serviço do docker"
      service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: "Dando permissão ao usuário"
      command: "usermod -aG docker {{ USER }}"

    - name: "Subindo o redis"
      command: "docker run -d --volume /srv/docker/gitlab/redis:/var/lib/redis \
                  --restart=always \
                  --name=gitlab-redis \
                  sameersbn/redis:4.0.9-1"
    
    - name: "Subindo o PostgreSQL"
      command: "docker run -d --volume /srv/docker/gitlab/postgresql:/var/lib/postgresql \
                  --env 'DB_USER={{ DB_USER }}' \
                  --env 'DB_PASS={{ DB_PASS }}' \
                  --env 'DB_NAME={{ DB_NAME }}' \
                  --env 'DB_EXTENSION=pg_trgm' \
                  --restart=always \
                  --name=gitlab-postgresql \
                  sameersbn/postgresql:10"

    - name: "Subindo o Gitlab Runner"
      command: "docker run -d \
                  --volume /srv/gitlab-runner/config:/etc/gitlab-runner \
                  --volume /var/run/docker.sock:/var/run/docker.sock \
                  --restart=always \
                  --name=gitlab-runner \
                  gitlab/gitlab-runner:latest"

    - name: "Subindo o Gitlab"
      command: "docker run -d --volume /srv/docker/gitlab/gitlab:/home/git/data \
                  --link gitlab-postgresql:postgresql \
                  --link gitlab-redis:redisio \
                  --publish {{ HTTP_PORT }}:80 \
                  --publish {{ SSH_PORT }}:22 \
                  --env 'DEBUG=false' \
                  --env 'DB_ADAPTER=postgresql' \
                  --env 'DB_HOST=gitlab-postgresql' \
                  --env 'DB_PORT=5432' \
                  --env 'DB_USER={{ DB_USER }}' \
                  --env 'DB_PASS={{ DB_PASS }}' \
                  --env 'DB_NAME={{ DB_NAME }}' \
                  --env 'GITLAB_HOST={{ GITLAB_HOST }}' \
                  --env 'GITLAB_PORT={{ HTTP_PORT }}' \
                  --env 'GITLAB_SSH_PORT={{ SSH_PORT }}' \
                  --env 'GITLAB_SECRETS_DB_KEY_BASE={{ SECRETS_DB_KEY_BASE }}' \
                  --env 'GITLAB_SECRETS_SECRET_KEY_BASE={{ SECRETS_SECRET_KEY_BASE }}' \
                  --env 'GITLAB_SECRETS_OTP_KEY_BASE={{ SECRETS_OTP_KEY_BASE }}' \
                  --env 'GITLAB_ROOT_PASS={{ GITLAB_ROOT_PASS }}' \
                  --env 'GITLAB_HTTPS=false' \
                  --restart=always \
                  --name=gitlab \
                  sameersbn/gitlab:latest"

    - name: "Criando pasta para baixar os arquivos"
      file: path=/home/{{ USER }}/ansible-playbook state=directory

    - name: "Baixando e descompactando o OpenShift Client Tools (OC)"
      unarchive:
        src: https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-server-v3.11.0-0cbc58b-linux-64bit.tar.gz
        dest: /home/{{ USER }}/ansible-playbook
        remote_src: yes

    - name: "Movendo executável para $PATH"
      command: "cp /home/{{ USER }}/ansible-playbook/openshift-origin-server-v3.11.0-0cbc58b-linux-64bit/oc /usr/local/bin/"
